name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
       
          docker build -t my-python-app .
          docker run -p 80:80 my-python-app



     
    
  
       
       

